// Local review UI for bench/SPOTCHECK.md: one screen per drawn item, the page under test beside the
// recorded label, and the verdict saved as you go. Nothing here judges anything -- it only shows what
// spotcheck.ts drew and records what the human says back.
//
//   npx tsx bench/spotcheck-ui.ts [--port 4174]     then open http://127.0.0.1:4174
//
// It serves the corpus itself (same MOUNTS as bench/serve.ts), so bench/serve.ts does NOT need to be
// running and the preview is same-origin, which is what lets it outline the target element.
// Verdicts land in bench/spotcheck-answers.json as you type; SPOTCHECK.md is only ever touched by the
// explicit "write into SPOTCHECK.md" action, because spotcheck.ts rewrites that file wholesale.
import { createHash } from "node:crypto";
import { createServer } from "node:http";
import {
  existsSync,
  readFileSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, extname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { MOUNTS, SERVE_ORIGIN } from "./serve.js";

const BENCH = dirname(fileURLToPath(import.meta.url));
const SPOTCHECK_MD = join(BENCH, "SPOTCHECK.md");
const ANSWERS_JSON = join(BENCH, "spotcheck-answers.json");
const DEFAULT_PORT = 4174;

const VERDICTS = ["agree", "disagree", "unsure"] as const;
const VerdictSchema = z.enum(VERDICTS);
export type Verdict = z.infer<typeof VerdictSchema>;

const AnswerSchema = z
  .object({ verdict: VerdictSchema.nullable(), note: z.string() })
  .strict();
const GenerationSchema = z
  .object({
    itemsSha256: z.string(),
    answers: z.record(z.string(), AnswerSchema),
  })
  .strict();

const AnswersFileSchema = z
  .object({
    // Which DRAWN ITEMS the CURRENT answers belong to: a redraw changes the items under the same
    // numbers, so answers carried across one would silently describe different elements. Keyed on
    // the items' own fields, NOT the file bytes -- writing verdicts back into the file changes its
    // bytes, and hashing those made the write invalidate the answers it had just saved.
    itemsSha256: z.string(),
    answers: z.record(z.string(), AnswerSchema),
    // Every earlier draw's verdicts, kept forever. Regenerating a worklist is an ordinary operation
    // (a different --sample, a re-run at a new sha), and it used to prune this file to nothing on
    // the next keystroke. The worklist is disposable; this file is the record. It only ever grows.
    superseded: z.array(GenerationSchema).default([]),
  })
  .strict();
export type AnswersFile = z.infer<typeof AnswersFileSchema>;

// Move the current generation into the archive and start a clean one. Never drops a verdict.
export function supersede(file: AnswersFile, key: string): AnswersFile {
  if (file.itemsSha256 === key) return file;
  const hadAnswers = Object.keys(file.answers).length > 0;
  return {
    itemsSha256: key,
    answers: {},
    superseded: hadAnswers
      ? [...file.superseded, { itemsSha256: file.itemsSha256, answers: file.answers }]
      : file.superseded,
  };
}

export type SpotUiItem = {
  n: number;
  group: string;
  title: string;
  url: string | null;
  selector: string | null;
  test: string;
  recorded: string;
  // What the file already records for this item. The write guard used the checkbox as its only
  // proxy for "already answered", so it was blind to a verdict typed straight into the markdown --
  // and erased it while reporting success.
  answered: boolean;
  answerLine: string;
};

// SPOTCHECK.md is generated by spotcheck.ts as a fixed five-line block per item (its renderer writes
// the number + checkbox + title, then open / test / recorded / agree lines).
export function parseSpotcheck(md: string): SpotUiItem[] {
  const items: SpotUiItem[] = [];
  let group = "";
  let cur: SpotUiItem | null = null;
  // Both start patterns end `(.*)$`, and in JS `.` does not match \r while `$` is not multiline, so
  // a CRLF worklist parsed to zero items and the UI reported "No items found".
  md = md.replace(/\r\n?/g, "\n");
  const push = (): void => {
    if (cur !== null) items.push(cur);
    cur = null;
  };
  for (const line of md.split("\n")) {
    const heading = /^##\s+(.*)$/.exec(line);
    if (heading) {
      push();
      group = heading[1].trim();
      continue;
    }
    const start = /^(\d+)\.\s+\[[ xX]\]\s+(.*)$/.exec(line);
    if (start) {
      push();
      cur = {
        n: Number(start[1]),
        group,
        title: start[2].trim(),
        url: null,
        selector: null,
        test: "",
        recorded: "",
        answered: /\[[xX]\]/.test(line),
        answerLine: "",
      };
      continue;
    }
    if (cur === null) continue;
    const open = /^\s+-\s+open\s+(.*)$/.exec(line);
    if (open) {
      cur.url = /<([^>]+)>/.exec(open[1])?.[1] ?? null;
      cur.selector = selectorFrom(/`([^`]+)`/.exec(open[1])?.[1] ?? null);
      continue;
    }
    const test = /^\s+-\s+test:\s*(.*)$/.exec(line);
    if (test) {
      cur.test = test[1].trim();
      continue;
    }
    const recorded = /^\s+-\s+recorded:\s*(.*)$/.exec(line);
    if (recorded) {
      cur.recorded = recorded[1].trim();
      continue;
    }
    const agree = /^\s+-\s+agree\?\s*\/\s*note:\s*(.*)$/.exec(line);
    if (agree) cur.answerLine = agree[1].trim();
  }
  push();
  return items;
}

// spotcheck.ts writes a BAD-element item as a url plus a CONSOLE EXPRESSION in backticks
// (`document.querySelectorAll("...").length`), not a bare selector. Handing that to querySelector
// throws, so the preview silently outlined nothing on those items. Pull the selector back out.
function selectorFrom(code: string | null): string | null {
  if (code === null) return null;
  const call = /querySelector(?:All)?\(\s*(["'])((?:\\.|(?!\1).)*)\1\s*\)/.exec(code);
  if (call) {
    try {
      return JSON.parse(`"${call[2].replace(/"/g, '\\"')}"`) as string;
    } catch {
      return call[2];
    }
  }
  // Anything still carrying JS syntax is not a selector; better no outline than a thrown one.
  return /[(){};]|=>/.test(code) ? null : code;
}

// Fills the "- agree? / note:" slot and ticks the box, leaving every other byte alone.
export function mergeIntoMd(
  md: string,
  answers: Record<string, { verdict: Verdict | null; note: string }>,
): string {
  let n: string | null = null;
  return md
    .split("\n")
    .map((line) => {
      // Any numbered line begins a new item, even one this writer does not recognise. Resetting
      // only on recognised ones meant the next "agree? / note:" after an odd checkbox was still
      // attributed to the PREVIOUS item -- a verdict written onto the wrong flag.
      const numbered = /^(\d+)\.\s/.test(line);
      const start = /^(\d+)\.\s+\[([ xX])\]\s+(.*)$/.exec(line);
      if (start) {
        n = start[1];
        return `${start[1]}. [${answers[n]?.verdict != null ? "x" : " "}] ${start[3]}`;
      }
      if (numbered) {
        n = null;
        return line;
      }
      if (n !== null && /^\s+-\s+agree\?\s*\/\s*note:/.test(line)) {
        const a = answers[n];
        const said = a?.verdict == null ? "" : ` ${a.verdict}`;
        // Collapse all whitespace: a note containing a newline would otherwise be written as extra
        // lines, and one shaped like "2. [x] **x**" would forge an item the reviewer never saw.
        const note = a?.note.trim()
          ? ` — ${a.note.trim().replace(/\s+/g, " ")}`
          : "";
        return `    - agree? / note:${said}${note}`;
      }
      return line;
    })
    .join("\n");
}

const sha256 = (s: string): string =>
  createHash("sha256").update(s).digest("hex");

// Identity of the drawn set: everything the generator chose, and nothing that a verdict, a parser
// improvement or the serving port can change.
//   - the url is reduced to its PATH: blind-labels.ts re-points local urls at whatever port the
//     reviewer runs on, and keying on the origin discarded the record when that port changed.
//   - the selector is excluded: it is parsed out of the open line, so improving the parser would
//     otherwise silently invalidate a completed record.
// An empty parse throws rather than keying as sha256(""), which every broken file shared -- so one
// broken worklist could be shown, and overwritten, with another's verdicts.
export function itemsKey(items: readonly SpotUiItem[]): string {
  if (items.length === 0)
    throw new Error("refusing to key an empty worklist: nothing was drawn");
  const pathOf = (url: string | null): string => {
    if (url === null) return "";
    const m = /^[a-z]+:\/\/[^/]+(\/.*)$/i.exec(url);
    return m === null ? url : m[1];
  };
  return sha256(
    items
      .map((i) => [i.n, i.title, pathOf(i.url), i.test, i.recorded].join("\u0000"))
      .join("\n"),
  );
}

function readAnswers(answersPath: string, spotSha: string): AnswersFile {
  const empty: AnswersFile = {
    itemsSha256: spotSha,
    answers: {},
    superseded: [],
  };
  if (!existsSync(answersPath)) return empty;
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(answersPath, "utf8"));
  } catch {
    // A truncated file is somebody's record, damaged. Refuse loudly rather than starting a clean
    // one over the top of it.
    throw new Error(
      `${answersPath} is not valid JSON. It holds the verdict record; move it aside deliberately rather than letting this overwrite it.`,
    );
  }
  const parsed = AnswersFileSchema.safeParse(raw);
  if (!parsed.success) throw new Error(`${answersPath} does not match the answers schema`);
  // A redraw remaps numbers to different items, so its answers must not be SHOWN -- but they are
  // still a human's work and are moved to `superseded` rather than dropped.
  return supersede(parsed.data, spotSha);
}

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".gif": "image/gif",
  ".woff2": "font/woff2",
};

function staticFile(pathname: string): { body: Buffer; type: string } | null {
  const prefix = Object.keys(MOUNTS).find((p) => pathname.startsWith(p));
  if (prefix === undefined) return null;
  const root = resolve(MOUNTS[prefix as keyof typeof MOUNTS]);
  const file = resolve(join(root, pathname.slice(prefix.length)));
  // Refuse anything that escapes its mount.
  if (file !== root && !file.startsWith(root + sep)) return null;
  // realpath before the check: resolve()/join() are string operations and readFileSync follows
  // symlinks, so a link inside a mount would otherwise read straight through it.
  let real: string;
  try {
    real = realpathSync(file);
  } catch {
    return null;
  }
  if (real !== root && !real.startsWith(root + sep)) return null;
  // A directory (e.g. GET /corpus/, which resolves to the mount root) is not a file: readFileSync
  // would throw EISDIR out of the request handler and take the whole review server down mid-review.
  if (!statSync(real).isFile()) return null;
  return {
    body: readFileSync(real),
    type: MIME[extname(real).toLowerCase()] ?? "application/octet-stream",
  };
}

function main(argv: readonly string[]): void {
  const portFlag = argv.indexOf("--port");
  const port =
    portFlag === -1 ? DEFAULT_PORT : Number(argv[portFlag + 1] ?? DEFAULT_PORT);
  if (!Number.isInteger(port) || port <= 0) {
    console.error("--port must be a positive integer");
    process.exit(2);
  }
  // --file lets the same reviewer drive any spotcheck-shaped worklist (e.g. BLIND-LABELS.md);
  // each worklist keeps its verdicts in its own <name>-answers.json.
  const fileFlag = argv.indexOf("--file");
  const mdPath =
    fileFlag === -1 ? SPOTCHECK_MD : resolve(argv[fileFlag + 1] ?? SPOTCHECK_MD);
  const answersPath =
    fileFlag === -1
      ? ANSWERS_JSON
      : mdPath.replace(/\.md$/i, "") + "-answers.json";
  if (!existsSync(mdPath)) {
    console.error(
      `${mdPath} does not exist. Draw it first: npx tsx bench/spotcheck.ts`,
    );
    process.exit(2);
  }
  const origin = `http://127.0.0.1:${port}`;

  const server = createServer((req, res) => {
    const url = new URL(req.url ?? "/", origin);
    const send = (code: number, type: string, body: string | Buffer): void => {
      res.writeHead(code, {
        "content-type": type,
        "cache-control": "no-store",
      });
      res.end(body);
    };

    if (url.pathname === "/" || url.pathname === "/index.html")
      return send(200, "text/html; charset=utf-8", PAGE);

    if (url.pathname === "/api/items") {
      const md = readFileSync(mdPath, "utf8");
      const drawn = parseSpotcheck(md);
      // Key on the drawn items, BEFORE the preview url is rewritten below: the identity of an item
      // is what spotcheck.ts chose, not which port this process happens to serve it on.
      const key = itemsKey(drawn);
      const items = drawn.map((i) => ({
        ...i,
        // Point the preview at this server so it is same-origin and the target can be outlined.
        url: i.url === null ? null : i.url.replace(SERVE_ORIGIN, origin),
      }));
      return send(
        200,
        MIME[".json"],
        JSON.stringify({ items, ...readAnswers(answersPath, key) }),
      );
    }

    if (url.pathname === "/api/answer" && req.method === "POST") {
      let raw = "";
      req.on("data", (c) => (raw += c));
      req.on("end", () => {
        const parsed = z
          .object({
            n: z.number().int().positive(),
            verdict: VerdictSchema.nullable(),
            note: z.string(),
            // Which draw the reviewer was looking at when they judged.
            itemsSha256: z.string(),
          })
          .strict()
          .safeParse(JSON.parse(raw || "{}"));
        if (!parsed.success)
          return send(400, MIME[".json"], JSON.stringify({ ok: false }));
        const spotSha = itemsKey(parseSpotcheck(readFileSync(mdPath, "utf8")));
        // If the worklist was regenerated while this page was open, item 7 on screen is not item 7
        // on disk. Accepting the verdict would file a judgement against a flag nobody looked at.
        if (parsed.data.itemsSha256 !== spotSha)
          return send(
            409,
            MIME[".json"],
            JSON.stringify({
              ok: false,
              reason:
                "the worklist changed since this page was loaded; reload before judging further (nothing was saved, and no earlier verdict was lost)",
            }),
          );
        const file = readAnswers(answersPath, spotSha);
        file.answers[String(parsed.data.n)] = {
          verdict: parsed.data.verdict,
          note: parsed.data.note,
        };
        writeFileSync(answersPath, `${JSON.stringify(file, null, 2)}\n`);
        send(200, MIME[".json"], JSON.stringify({ ok: true }));
      });
      return;
    }

    if (url.pathname === "/api/write-md" && req.method === "POST") {
      const md = readFileSync(mdPath, "utf8");
      const file = readAnswers(answersPath, itemsKey(parseSpotcheck(md)));
      const done = Object.values(file.answers).filter(
        (a) => a.verdict !== null,
      ).length;
      // mergeIntoMd rewrites every checkbox and every answer line from the json, so anything the
      // file already records but the json does not would be erased. Refuse unless the json is a
      // superset of what is already written: saving must never subtract.
      // "Already recorded" means a ticked box OR text on the answer line -- these files are meant
      // to be fillable by hand (SPOTCHECK.md's own header describes a DevTools walk and never
      // mentions this tool), and judging only by the checkbox erased hand-written verdicts.
      const already = parseSpotcheck(md).filter(
        (i) => i.answered || i.answerLine !== "",
      );
      const wouldLose = already.filter((i) => {
        const a = file.answers[String(i.n)];
        if (a?.verdict == null) return true;
        // Writing would also drop reasoning the file carries and the record does not.
        const carried = `${a.verdict}${a.note.trim() ? ` — ${a.note.trim().replace(/\s+/g, " ")}` : ""}`;
        return i.answerLine !== "" && i.answerLine !== carried;
      });
      if (done === 0 || wouldLose.length > 0)
        return send(
          200,
          MIME[".json"],
          JSON.stringify({
            ok: false,
            done,
            reason:
              done === 0
                ? "no verdicts to write"
                : `refusing: ${wouldLose.length} item(s) already answered in the file have no verdict here (${wouldLose.map((i) => i.n).join(", ")})`,
          }),
        );
      writeFileSync(mdPath, mergeIntoMd(md, file.answers));
      return send(200, MIME[".json"], JSON.stringify({ ok: true, done }));
    }

    const file = staticFile(url.pathname);
    if (file) return send(200, file.type, file.body);
    send(404, "text/plain; charset=utf-8", "not found");
  });

  server.on("error", (e: NodeJS.ErrnoException) => {
    console.error(
      e.code === "EADDRINUSE"
        ? `port ${port} is in use — this UI is probably already running at ${origin}. Open it, or pass --port <other>.`
        : e,
    );
    process.exitCode = 1;
  });
  server.listen(port, "127.0.0.1", () => {
    console.log(`spot-check UI  ${origin}`);
    console.log(`  items    ${mdPath}`);
    console.log(`  verdicts ${answersPath} (saved as you type)`);
    console.log("  Ctrl+C to stop");
  });
}

const PAGE = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Spot-check</title>
<style>
  :root {
    --bg: #f6f7f9; --panel: #fff; --ink: #14171a; --muted: #5b6570; --line: #dfe3e8;
    --accent: #2f6feb; --agree: #12805c; --disagree: #c2410c; --unsure: #8250df;
    --code-bg: #f0f2f5;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --bg: #0f1216; --panel: #161a20; --ink: #e8ecf1; --muted: #9aa5b1; --line: #2a313a;
      --accent: #6ea0ff; --agree: #3dd9a4; --disagree: #ff9e64; --unsure: #c4a7ff;
      --code-bg: #1d232b;
    }
  }
  :root[data-theme="dark"] {
    --bg: #0f1216; --panel: #161a20; --ink: #e8ecf1; --muted: #9aa5b1; --line: #2a313a;
    --accent: #6ea0ff; --agree: #3dd9a4; --disagree: #ff9e64; --unsure: #c4a7ff;
    --code-bg: #1d232b;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--ink);
    font: 15px/1.55 ui-sans-serif, -apple-system, "Segoe UI", system-ui, sans-serif;
  }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  .wrap { display: grid; grid-template-columns: 250px minmax(0,1fr); min-height: 100vh; }
  @media (max-width: 860px) {
    .wrap { grid-template-columns: 1fr; }
    aside { position: static !important; height: auto !important; }
  }
  aside {
    border-right: 1px solid var(--line); background: var(--panel);
    position: sticky; top: 0; height: 100vh; overflow-y: auto; padding: 14px 12px;
  }
  .brand { font-weight: 650; letter-spacing: -.01em; margin: 0 0 2px; }
  .progress { color: var(--muted); font-size: 13px; }
  .bar { height: 5px; border-radius: 3px; background: var(--code-bg); overflow: hidden; margin: 8px 0 14px; }
  .bar > i { display: block; height: 100%; background: var(--accent); width: 0; transition: width .2s; }
  .grp { font-size: 11px; text-transform: uppercase; letter-spacing: .07em; color: var(--muted); margin: 14px 0 6px; }
  .grp.held::after { content: " · held out"; color: var(--unsure); }
  nav button {
    display: flex; gap: 8px; align-items: center; width: 100%; text-align: left;
    background: none; border: 0; border-radius: 7px; padding: 6px 8px; cursor: pointer;
    color: var(--ink); font: inherit; font-size: 13px;
  }
  nav button:hover { background: var(--code-bg); }
  nav button[aria-current="true"] { background: var(--accent); color: #fff; }
  nav button[aria-current="true"] .dot { border-color: #fff; }
  nav button[aria-current="true"] .num { color: #fff; }
  .dot { width: 9px; height: 9px; border-radius: 50%; border: 1.5px solid var(--muted); flex: none; }
  .dot.agree { background: var(--agree); border-color: var(--agree); }
  .dot.disagree { background: var(--disagree); border-color: var(--disagree); }
  .dot.unsure { background: var(--unsure); border-color: var(--unsure); }
  .num { color: var(--muted); font-variant-numeric: tabular-nums; min-width: 18px; }
  .label { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  main { padding: 22px 26px 60px; max-width: 1060px; }
  @media (max-width: 600px) { main { padding: 16px; } }
  h1 { font-size: 20px; margin: 0 0 4px; letter-spacing: -.015em; }
  .sub { color: var(--muted); font-size: 13px; margin-bottom: 18px; }
  .card { background: var(--panel); border: 1px solid var(--line); border-radius: 11px; padding: 16px 18px; margin-bottom: 14px; }
  .card h2 { font-size: 12px; text-transform: uppercase; letter-spacing: .07em; color: var(--muted); margin: 0 0 10px; }
  .target { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-top: 12px; }
  code.sel { background: var(--code-bg); padding: 3px 8px; border-radius: 6px; font-size: 13px; }
  .recorded { background: var(--code-bg); border-radius: 8px; padding: 12px 14px; font-size: 14px; }
  .test { font-size: 14px; margin: 0; }
  .btns { display: flex; flex-wrap: wrap; gap: 8px; }
  button.v {
    font: inherit; font-weight: 550; padding: 9px 16px; border-radius: 8px; cursor: pointer;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink);
  }
  button.v:hover { border-color: var(--muted); }
  button.v[aria-pressed="true"] { color: #fff; border-color: transparent; }
  button.v.agree[aria-pressed="true"] { background: var(--agree); }
  button.v.disagree[aria-pressed="true"] { background: var(--disagree); }
  button.v.unsure[aria-pressed="true"] { background: var(--unsure); }
  a.open, button.ghost {
    font: inherit; display: inline-flex; align-items: center; gap: 6px; text-decoration: none;
    padding: 9px 15px; border-radius: 8px; border: 1px solid var(--line);
    background: var(--panel); color: var(--ink); cursor: pointer;
  }
  a.open { background: var(--accent); color: #fff; border-color: transparent; font-weight: 550; }
  textarea {
    width: 100%; min-height: 70px; resize: vertical; font: inherit; padding: 10px 12px;
    border-radius: 8px; border: 1px solid var(--line); background: var(--bg); color: var(--ink);
  }
  .warn { border-left: 3px solid var(--unsure); padding-left: 12px; color: var(--muted); font-size: 13px; margin: 12px 0 0; }
  iframe { width: 100%; height: 340px; border: 1px solid var(--line); border-radius: 8px; background: #fff; }
  .row { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; justify-content: space-between; }
  .hint { color: var(--muted); font-size: 12px; }
  kbd { background: var(--code-bg); border: 1px solid var(--line); border-bottom-width: 2px; border-radius: 4px; padding: 1px 5px; font-size: 11px; font-family: ui-monospace, monospace; }
  .saved { color: var(--agree); font-size: 12px; opacity: 0; transition: opacity .2s; }
  .saved.on { opacity: 1; }
</style>
</head>
<body>
<div class="wrap">
  <aside>
    <p class="brand">Spot-check</p>
    <div class="progress" id="prog">loading…</div>
    <div class="bar"><i id="barfill"></i></div>
    <nav id="nav"></nav>
  </aside>
  <main><div id="detail"></div></main>
</div>
<script>
const state = { items: [], answers: {}, cur: 0, itemsSha256: null };
const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;" }[c]));
// spotcheck.ts escapes angle brackets for markdown (\<button>); undo that for display.
const unmd = (s) => String(s ?? "").replace(/\\([<>\u0060*_])/g, "$1");
const rich = (s) => esc(unmd(s)).replace(/\u0060([^\u0060]+)\u0060/g, '<code class="sel">$1</code>');
const isHeld = (group) => /BAD/i.test(group);

async function load() {
  const d = await (await fetch("/api/items")).json();
  state.items = d.items;
  state.answers = d.answers || {};
  state.itemsSha256 = d.itemsSha256;
  const first = state.items.findIndex((i) => !state.answers[i.n] || !state.answers[i.n].verdict);
  state.cur = first === -1 ? 0 : first;
  render();
}

function render() {
  const total = state.items.length;
  const done = state.items.filter((i) => state.answers[i.n] && state.answers[i.n].verdict).length;
  document.getElementById("prog").textContent = done + " of " + total + " marked";
  document.getElementById("barfill").style.width = total ? (done / total * 100) + "%" : "0";

  const nav = document.getElementById("nav");
  nav.innerHTML = "";
  let group = null;
  state.items.forEach((it, idx) => {
    if (it.group !== group) {
      group = it.group;
      const h = document.createElement("div");
      h.className = "grp" + (isHeld(group) ? " held" : "");
      h.textContent = group.replace(/\s*\(.*$/, "");
      nav.appendChild(h);
    }
    const b = document.createElement("button");
    b.setAttribute("aria-current", String(idx === state.cur));
    const dot = document.createElement("span");
    dot.className = "dot " + ((state.answers[it.n] && state.answers[it.n].verdict) || "");
    const num = document.createElement("span");
    num.className = "num";
    num.textContent = it.n;
    const lab = document.createElement("span");
    lab.className = "label";
    lab.textContent = it.title.replace(/\*\*/g, "").split(" · ")[0];
    b.append(dot, num, lab);
    b.onclick = () => { state.cur = idx; render(); };
    nav.appendChild(b);
  });

  const it = state.items[state.cur];
  const detail = document.getElementById("detail");
  if (!it) { detail.textContent = "No items found in SPOTCHECK.md."; return; }
  const a = state.answers[it.n] || { verdict: null, note: "" };

  detail.innerHTML = [
    "<h1>" + it.n + ". " + rich(it.title) + "</h1>",
    '<div class="sub">' + esc(it.group) + "</div>",
    '<div class="card"><h2>What was recorded</h2><div class="recorded">' + rich(it.recorded) + "</div></div>",
    '<div class="card"><h2>How to test it</h2><p class="test">' + rich(it.test) + "</p>",
    it.url
      ? '<div class="target"><a class="open" href="' + esc(it.url) + '" target="_blank" rel="noopener">Open the page ↗</a>' +
        (it.selector ? '<span class="hint">then find</span><code class="sel">' + esc(it.selector) + "</code>" : "") + "</div>"
      : "",
    '<p class="warn">Do the Tab walk in the opened tab, not in the preview below — inside a frame, Tab carries on into this page, so you would be testing the wrong thing.</p></div>',
    it.url
      ? '<div class="card"><div class="row"><h2 style="margin:0">Preview' + (it.selector ? " — target outlined" : "") +
        '</h2><button class="ghost" id="reload">Reload preview</button></div>' +
        '<iframe id="prev" src="' + esc(it.url) + '" title="page under test"></iframe></div>'
      : "",
    '<div class="card"><h2>Your verdict</h2><div class="btns">',
    ["agree", "disagree", "unsure"].map((v) =>
      '<button class="v ' + v + '" data-v="' + v + '" aria-pressed="' + (a.verdict === v) + '">' +
      (v === "agree" ? "Agree" : v === "disagree" ? "Disagree" : "Not sure") + "</button>").join(""),
    "</div>",
    '<p class="hint" style="margin:12px 0 6px">Note — what you actually saw' +
      (isHeld(it.group) ? " (held-out item: keep this out of chat)" : "") + "</p>",
    '<textarea id="note" placeholder="e.g. took focus on the 2nd Tab, Enter did nothing">' + esc(a.note) + "</textarea>",
    '<div class="row" style="margin-top:12px"><div class="btns">' +
      '<button class="ghost" id="prevbtn">← Previous</button><button class="ghost" id="nextbtn">Next →</button></div>' +
      '<span class="saved" id="saved">saved</span></div></div>',
    '<div class="card"><div class="row"><div><h2 style="margin:0 0 4px">When you are done</h2>' +
      '<span class="hint">Verdicts save to spotcheck-answers.json as you type. This copies them into SPOTCHECK.md.</span></div>' +
      '<button class="ghost" id="writemd">Write into SPOTCHECK.md</button></div></div>',
    '<p class="hint"><kbd>1</kbd> agree &middot; <kbd>2</kbd> disagree &middot; <kbd>3</kbd> not sure &middot; <kbd>←</kbd><kbd>→</kbd> move &middot; <kbd>o</kbd> open page</p>',
  ].join("");

  detail.querySelectorAll("button.v").forEach((b) => { b.onclick = () => mark(b.dataset.v); });
  const note = document.getElementById("note");
  let t;
  note.oninput = () => {
    clearTimeout(t);
    t = setTimeout(() => save(it.n, (state.answers[it.n] || {}).verdict || null, note.value), 300);
  };
  document.getElementById("prevbtn").onclick = () => move(-1);
  document.getElementById("nextbtn").onclick = () => move(1);
  document.getElementById("writemd").onclick = writeMd;
  const rl = document.getElementById("reload");
  if (rl) rl.onclick = () => { const f = document.getElementById("prev"); f.src = f.src; };
  const frame = document.getElementById("prev");
  if (frame && it.selector) frame.onload = () => outline(frame, it.selector);
}

// Same-origin preview, so the target can be pointed at instead of hunted for in DevTools.
function outline(frame, selector) {
  try {
    const el = frame.contentDocument && frame.contentDocument.querySelector(selector);
    if (!el) return;
    el.style.outline = "3px solid #c2410c";
    el.style.outlineOffset = "2px";
    el.scrollIntoView({ block: "center" });
  } catch (e) { /* blocked: the preview still renders, just without the outline */ }
}

function mark(v) {
  const it = state.items[state.cur];
  const cur = (state.answers[it.n] || {}).verdict;
  const next = cur === v ? null : v;
  const note = document.getElementById("note").value;
  save(it.n, next, note);
  render();
  if (next) setTimeout(() => move(1), 180);
}

function move(d) {
  const n = state.cur + d;
  if (n < 0 || n >= state.items.length) return;
  state.cur = n;
  render();
}

async function save(n, verdict, note) {
  state.answers[n] = { verdict: verdict, note: note };
  const r = await fetch("/api/answer", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ n: n, verdict: verdict, note: note, itemsSha256: state.itemsSha256 }),
  });
  const s = document.getElementById("saved");
  if (!r.ok) {
    // The worklist changed underneath this page. Say so instead of letting the reviewer keep
    // judging into a void.
    const d = await r.json().catch(() => ({}));
    if (s) { s.textContent = d.reason || "not saved — reload"; s.style.color = "var(--disagree)"; s.classList.add("on"); }
    return;
  }
  if (s) { s.classList.add("on"); setTimeout(() => s.classList.remove("on"), 900); }
}

async function writeMd() {
  const d = await (await fetch("/api/write-md", { method: "POST" })).json();
  // A real alert() would freeze the page against automation; say it on the button instead.
  const el = document.getElementById("writemd");
  const old = el.textContent;
  el.textContent = d.ok ? "Wrote " + d.done + " verdict(s)" : "Could not write";
  setTimeout(() => { el.textContent = old; }, 2200);
}

addEventListener("keydown", (e) => {
  const tag = document.activeElement ? document.activeElement.tagName : "";
  if (tag === "INPUT" || tag === "TEXTAREA") return;
  if (e.key === "1") mark("agree");
  else if (e.key === "2") mark("disagree");
  else if (e.key === "3") mark("unsure");
  else if (e.key === "ArrowRight") move(1);
  else if (e.key === "ArrowLeft") move(-1);
  else if (e.key === "o") {
    const it = state.items[state.cur];
    if (it && it.url) window.open(it.url, "_blank", "noopener");
  }
});

load();
</script>
</body>
</html>`;

const invokedDirectly =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) main(process.argv.slice(2));
