load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "pagefinder",
    srcs = [
        "__init__.py",
        "crawler.py",
        "main.py",
        "markov.py",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("aiohttp"),
        requirement("beautifulsoup4"),
        requirement("numpy"),
        requirement("openai"),
    ],
)

py_binary(
    name = "cli",
    srcs = ["__main__.py"],
    main = "__main__.py",
    visibility = ["//visibility:public"],
    deps = [":pagefinder"],
)
