import * as fs from 'fs';
import * as path from 'path';

async function main() {
  const chalk = (await import('chalk')).default;
  
  const reportPath = process.argv[2];
  if (!reportPath) {
    console.error(chalk.red('Usage: npm run visualize-report <path-to-json-report>'));
    process.exit(1);
  }

  if (!fs.existsSync(reportPath)) {
    console.error(chalk.red(`File not found: ${reportPath}`));
    process.exit(1);
  }

  try {
    const report = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));
    const html = generateHtml(report);
    
    const outputPath = reportPath.replace('.json', '.html');
    fs.writeFileSync(outputPath, html);
    
    console.log(chalk.green(`
✨ Report visualizer generated at: ${chalk.bold(outputPath)}`));
    console.log(chalk.blue(`Open this file in your browser to view the report.`));

  } catch (error: any) {
    console.error(chalk.red('Failed to generate report:'), error.message);
    process.exit(1);
  }
}

function generateHtml(report: any): string {
  const scoreColor = report.score >= 80 ? '#10b981' : report.score >= 50 ? '#f59e0b' : '#ef4444'; // Green, Amber, Red
  
  // Flatten violations if they are in categories, or use them directly if they are at the root
  let allViolations: any[] = [];
  if (report.violations) {
      allViolations = report.violations;
  } else if (report.categories) {
      report.categories.forEach((cat: any) => {
          if (cat.violations) {
              allViolations.push(...cat.violations.map((v: any) => ({ ...v, category: cat.name })));
          }
      });
  }

  // Sort by severity
  const severityOrder: Record<string, number> = { 'Critical': 0, 'Major': 1, 'Minor': 2 };
  allViolations.sort((a, b) => (severityOrder[a.severity] ?? 3) - (severityOrder[b.severity] ?? 3));

  const violationCards = allViolations.map((v: any, index: number) => {
    const sevClass = v.severity?.toLowerCase() || 'minor';
    const sevLabelColor = v.severity === 'Critical' ? 'bg-red-100 text-red-800' : v.severity === 'Major' ? 'bg-orange-100 text-orange-800' : 'bg-blue-100 text-blue-800';
    
    return (
      `
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-4 transition hover:shadow-md">
        <div class="flex items-start justify-between mb-2">
          <div class="flex items-center gap-3">
            <span class="px-2.5 py-0.5 rounded-full text-xs font-medium ${sevLabelColor}">
              ${v.severity || 'Issue'}
            </span>
            <span class="text-sm text-gray-500 font-mono">
              ${v.wcag_article || 'General'}
            </span>
            ${v.category ? `<span class="text-xs text-gray-400 bg-gray-100 px-2 py-0.5 rounded">${v.category}</span>` : ''}
          </div>
          <span class="text-xs text-gray-400">#${index + 1}</span>
        </div>
        
        <h3 class="text-lg font-semibold text-gray-900 mb-2">
          ${v.description}
        </h3>

        ${v.location ? (
        `<div class="mb-3 text-sm text-gray-600 bg-gray-50 p-2 rounded border border-gray-100">
          <span class="font-medium text-gray-700">📍 Location:</span> <span class="font-mono text-xs">${v.location}</span>
        </div>`
        ) : ''}

        ${v.recommendation ? (
        `<div class="mt-3 text-sm">
          <span class="font-medium text-emerald-700">💡 Recommendation:</span>
          <p class="text-gray-700 mt-1">${v.recommendation}</p>
        </div>`
        ) : ''}
      </div>
    `
    );
  }).join('');

  return (
    `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accessibility Audit Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Inter', sans-serif; }
    </style>
</head>
<body class="bg-gray-50 min-h-screen p-8">
    <div class="max-w-4xl mx-auto">
        <!-- Header -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-8">
            <div class="flex items-center justify-between">
                <div>
                    <h1 class="text-3xl font-bold text-gray-900 tracking-tight">Accessibility Audit</h1>
                    <p class="text-gray-500 mt-1">Generated by AT Agent</p>
                </div>
                <div class="text-center">
                    <div class="text-5xl font-bold mb-1" style="color: ${scoreColor}">${report.score}</div>
                    <div class="text-sm font-medium text-gray-400 uppercase tracking-wide">Score</div>
                </div>
            </div>
            
            ${report.summary ? (
            `<div class="mt-6 pt-6 border-t border-gray-100">
                <h2 class="text-sm font-semibold text-gray-900 uppercase tracking-wide mb-2">Executive Summary</h2>
                <p class="text-gray-600 leading-relaxed">${report.summary}</p>
            </div>`
            ) : ''}
        </div>

        <!-- Violations -->
        <div class="mb-6 flex items-center justify-between">
            <h2 class="text-xl font-bold text-gray-800">Violations Found</h2>
            <span class="text-sm text-gray-500 bg-white px-3 py-1 rounded-full border border-gray-200 shadow-sm">${allViolations.length} Issues</span>
        </div>

        <div class="space-y-4">
            ${violationCards || '<div class="text-center py-12 text-gray-500">No violations found! Great job. 🎉</div>'}
        </div>
        
        <div class="mt-12 text-center text-xs text-gray-400">
            Generated on ${new Date().toLocaleString()}
        </div>
    </div>
</body>
</html>
  `
  );
}

main();
